# Spring Boot Application
spring.application.name=online-food-delivery

# Server Port
server.port=8081

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/online_food_delivery

# JWT Configuration
jwt.secret=MyFoodDeliveryApplicationSecretKeyForJWT2026Secure
jwt.expiration=86400000